### PR TITLE
fix(example_group): fix RSpec3 deprecation error when determining example file path

### PR DESCRIPTION
**Pull request by booleanbetrayal**
Fixes https://github.com/sj26/rspec_junit_formatter/issues/28

Not too familiar with RSpec API, but this seems proper to me. Would be nice to bump the version again, if this gets merged.

### CODE REVIEW

**Comment by booleanbetrayal** [comment]
@sj26 - let me know if you have any questions!

**Comment by suweller** [comment]
:+1:

**Comment by booleanbetrayal** [comment]
Would be great to get this in!

**Comment by suweller** [comment]
This makes all Rspec builds on CircleCi that `raise_errors_for_deprecations!` fail. Future Rspec versions of rspec may not even be able to access metadata that way.

**Comment by suweller** [comment]
Let me clarify, this pull-request actually addresses what I've explained before. The current formatter breaks when `raise_errors_for_deprecations!` is used. CircleCi depends on this formatter, which is why any rspec testsuite running on CircleCi depends on it.

**Comment by sj26** [comment]
I trust you!

**Comment by booleanbetrayal** [comment]
:+1:

**Pull request merged**
