### PR TITLE
Add file information to XML report

### PR DESCRIPTION
**Pull request by marcomorain**
This PR adds file information to the XML report to make it easier for tools like CircleCI to produce helpful build reports.

### CODE REVIEW

**Comment by marcomorain** [comment]
Hi @sj26 – is this something you are willing to accept into rspec_junit_formatter?

**Comment by sj26** [comment]
Sorry, I haven't been getting new PR notifications for some reason which I hope has just been rectified.

Yes, this seems like a good PR. Why are you walking up to the example group path though? Should this include line number information as well?

**Comment by kylev** [comment]
@dwwoelfel or @marcomorain: Do you have an answer for @sj26's question? I think I know the answer, if you care to confirm...

I did some poking (because I'd like this to be merged) and discovered that when dealing with shared examples, the ExampleGroup handed to the `before(:each)` will be the definition file for the shared examples, not where the shared examples were used. So if you have `it_behaves_like 'a shape'` inside `square_spec.rb`, the ExampleGroup will refer to `shared_examples_for_shapes.rb`.

That isn't a relevant difference for junit-style output. Where the shared examples were called from is what is relevant, so recursing into the ExampleGroup metadata reveals the actual spec file the shared examples are being invoked from.

**Comment by kylev** [comment]
Re-ping @dwwoelfel and @marcomorain to see if they can comment on the walking the path.

I'd love to see this folded into an official release so I don't have to refer to a diverged fork at circleci/rspec_junit_formatter.

**Comment by marcomorain** [comment]
Hi guys - sorry for the delay on this – I get this emails into my personal github email address so they get buried in gmail.

**Comment by marcomorain** [comment]
@kylev @sj26 TBH I'm not that familair with the internals of rspec – @dwwoelfel wrote this and he has since moved on from CircleCI. My interest is in getting this merged upstream – so that you don;t have to use a fork, @kylev :)

@kylev do you have a better suggestion for how to handle this?

**Comment by kylev** [comment]
I can confirm that this patch works in my project that uses rspec 3.2 (and builds on CircleCI).

@sj26 can merge as is, or I'm going to generate and test a new version on several rspec variants that also takes circleci/rspec_junit_formatter#3 into account (a deprecation issue).

**Comment by kylev** [comment]
Actually, ignore circleci/rspec_junit_formatter#3. It seems to be a bad report or something. Maybe they were using a pre-release version? I can't repro their issue.

Merge this pull request as-is. It works as I described above: ascribing the test and runtime to the appropriate spec file (including when shared examples are in play). I tested it with a micro project against latest versions of rspec-core of each point release: 2.14.8, 3.0.4, 3.1.7 and 3.2.1.

:shipit: :smile:

**Comment by kylev** [comment]
Ping? This can be merged. It works on all modern rspec versions.

**Comment by cayennes** [comment]
Hi (also from CircleCI)

I wasn't around when @dwwoelfel wrote this either and I don't have much experience with rspec, but I believe @kylev's explanation is correct.  To elaborate on why we want the file where the test is defined rather than where the shared code is defined: the specific aim is to be able to collect info about how long each file takes to run, in order to distribute them better for running tests in parallel.  Our fork tends to get out of date, so it would be great if people could use the official version of the formatter and still get this functionality.

What do you think?

**Comment by kylev** [comment]
Yup. It's just a little thinger to make sure rspec shared examples are correctly attributed, time-wise.

:shipit:

**Comment by BBonifield** [comment]
@sj26 Can we :shipit: ? LGTM

**Comment by kylev** [comment]
So say we all?

**Comment by appplemac** [comment]
Hi there (I’m also from CircleCI),

@sj26 Sorry to bother you again, but what do you think about this?

**Comment by sj26** [comment]
I don't have an active test environment, so I'll trust you guys. :-)

**Comment by marcomorain** [comment]
Thanks for merging this.

**Comment by rahilsondhi** [comment]
Is it possible to get line numbers in the output?

**Comment by rahilsondhi** [comment]
Following up on my previous comment, I added this functionality in #38

**Pull request merged**
